receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  journald:
    directory: /var/log/journal
    units:
      - test-api.service
      - dora-exporter.service
      - prometheus.service
      - alertmanager.service
      - loki.service
      - tempo.service
      - grafana-server.service
    priority: info

processors:
  batch:
  resource:
    attributes:
      - key: service.name
        value: test-api
        action: upsert
      - key: deployment.environment
        value: production
        action: upsert

exporters:
  otlp/tempo:
    endpoint: 127.0.0.1:4319
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: http://127.0.0.1:3100/otlp

  prometheus:
    endpoint: 0.0.0.0:8889

  debug:
    verbosity: basic

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [journald]
      processors: [resource, batch]
      exporters: [otlphttp/loki]
